using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace AkriStat.Models
{
    public partial class MatchTeamStats
    {
        public int MatchID { get; set; }
        public int CompetitionID { get; set; }
        public DateTime Date { get; set; }
        public string Season { get; set; }
        public string Round { get; set; }
        public int? HomeTeamID { get; set; }
        public int TeamOneID { get; set; }
        public string TeamOneName { get; set; }
        public int TeamTwoID { get; set; }
        public string TeamTwoName { get; set; }
        public int? TeamOneGoals { get; set; }
        public int? TeamOneShots { get; set; }
        public int? TeamOneShotsOnTarget { get; set; }
        public double? TeamOneShotsOnTargetPercentage { get; set; }
        public double? TeamOneShotsPerTouch { get; set; }
        public double? TeamOneGoalsPerShot { get; set; }
        public int? TeamOnePenaltyKicksMade { get; set; }
        public int? TeamOnePenaltyKicksAttempted { get; set; }
        public double? TeamOnePenaltyKicksConversionRate { get; set; }
        public decimal? TeamOneXG { get; set; }
        public decimal? TeamOneNonPenaltyXG { get; set; }
        public double? TeamOneNonPenaltyXGPerShot { get; set; }
        public decimal? TeamOneGoalsMinusXG { get; set; }
        public decimal? TeamOneNonPenaltyGoalsMinusXG { get; set; }
        public int? TeamOneTouchesDefensivePenaltyArea { get; set; }
        public int? TeamOneTouchesDefensiveThird { get; set; }
        public int? TeamOneTouchesMiddleThird { get; set; }
        public int? TeamOneTouchesAttackingThird { get; set; }
        public int? TeamOneTouchesAttackingPenaltyArea { get; set; }
        public int? TeamOneTouches { get; set; }
        public int? TeamOneLiveBallTouches { get; set; }
        public int? TeamOneDribblesAttempted { get; set; }
        public int? TeamOneSuccessfulDribbles { get; set; }
        public double? TeamOneSuccessfulDribblesPercentage { get; set; }
        public int? TeamOnePlayersDribbledPast { get; set; }
        public int? TeamOnePassesReceived { get; set; }
        public double? TeamOnePassesReceivedPercentage { get; set; }
        public int? TeamOneMiscontrols { get; set; }
        public int? TeamOneDispossessed { get; set; }
        public int? TeamOnePassesAttemptedLiveBall { get; set; }
        public int? TeamOnePassesAttemptedDeadBall { get; set; }
        public int? TeamOnePassesAttemptedFreeKick { get; set; }
        public int? TeamOnePassesCompletedThroughBall { get; set; }
        public int? TeamOnePassesCompletedUnderPressure { get; set; }
        public int? TeamOneSwitches { get; set; }
        public int? TeamOneCrosses { get; set; }
        public int? TeamOneCornerKicks { get; set; }
        public int? TeamOneCornerKicksInswinging { get; set; }
        public int? TeamOneCornerKicksOutswinging { get; set; }
        public int? TeamOneCornerKicksStraight { get; set; }
        public int? TeamOnePassesGround { get; set; }
        public int? TeamOnePassesLow { get; set; }
        public int? TeamOnePassesHigh { get; set; }
        public int? TeamOnePassesLeftFoot { get; set; }
        public int? TeamOnePassesRightFoot { get; set; }
        public int? TeamOnePassesHeaded { get; set; }
        public int? TeamOnePassesThrowIn { get; set; }
        public int? TeamOnePassesOther { get; set; }
        public int? TeamOnePassesOffside { get; set; }
        public int? TeamOnePassesOutOfBounds { get; set; }
        public int? TeamOnePassesAttemptedIntercepted { get; set; }
        public int? TeamOnePassesAttemptedBlocked { get; set; }
        public int? TeamOnePassesCompleted { get; set; }
        public int? TeamOnePassesAttempted { get; set; }
        public double? TeamOnePassesCompletedPercentage { get; set; }
        public int? TeamOneYardsPassed { get; set; }
        public int? TeamOneYardsPassedProgressive { get; set; }
        public int? TeamOneShortPassesCompleted { get; set; }
        public int? TeamOneShortPassesAttempted { get; set; }
        public double? TeamOneShortPassesCompletedPercentage { get; set; }
        public int? TeamOneMediumPassesCompleted { get; set; }
        public int? TeamOneMediumPassesAttempted { get; set; }
        public double? TeamOneMediumPassesCompletedPercentage { get; set; }
        public int? TeamOneLongPassesCompleted { get; set; }
        public int? TeamOneLongPassesAttempted { get; set; }
        public double? TeamOneLongPassesCompletedPercentage { get; set; }
        public int? TeamOneAssists { get; set; }
        public decimal? TeamOneXGAssisted { get; set; }
        public int? TeamOneKeyPasses { get; set; }
        public int? TeamOneChancesCreated { get; set; }
        public int? TeamOnePassesIntoFinalThird { get; set; }
        public int? TeamOnePassesIntoPenaltyArea { get; set; }
        public int? TeamOneCrossesIntoPenaltyArea { get; set; }
        public int? TeamOneProgressivePasses { get; set; }
        public double? TeamOneProgressivePassesPercentage { get; set; }
        public int? TeamOneYellowCards { get; set; }
        public int? TeamOneRedCards { get; set; }
        public int? TeamOneFouls { get; set; }
        public int? TeamOneFoulsDrawn { get; set; }
        public int? TeamOneOffsides { get; set; }
        public int? TeamOnePenaltyKicksConceded { get; set; }
        public int? TeamOneOwnGoals { get; set; }
        public int? TeamOneLooseBallsRecovered { get; set; }
        public int? TeamOneAerialDualsWon { get; set; }
        public int? TeamOneAerialDualsLost { get; set; }
        public double? TeamOneAerialDualsWonPercentage { get; set; }
        public int? TeamOneGkGoalsConceded { get; set; }
        public int? TeamOneGkSaves { get; set; }
        public double? TeamOneGkSavesPercentage { get; set; }
        public int? TeamOneGkCleanSheets { get; set; }
        public decimal? TeamOneGkPostShotXG { get; set; }
        public int? TeamOneGkPassesCompletedOver40Yards { get; set; }
        public int? TeamOneGkPassesAttemptedOver40Yards { get; set; }
        public double? TeamOneGkPassesCompletedOver40YardsPercentage { get; set; }
        public int? TeamOneGkThrowsAttempted { get; set; }
        public double? TeamOneGkPassesAttemptedOver40YardsPercentage { get; set; }
        public int? TeamOneGkGoalKicksAttempted { get; set; }
        public int? TeamOneGkOpponentCrossesAttempted { get; set; }
        public double? TeamOneGkOpponentCrossesStoppedPercentage { get; set; }
        public int? TeamOneGkDefensiveActionsOutsidePenaltyArea { get; set; }
        public int? TeamOneShotCreatingActions { get; set; }
        public int? TeamOnePassesCompletedLiveBallLeadingToShot { get; set; }
        public int? TeamOnePassesCompletedDeadBallLeadingToShot { get; set; }
        public int? TeamOneDribblesLeadingToShot { get; set; }
        public int? TeamOneShotsLeadingToAnotherShot { get; set; }
        public int? TeamOneFoulsDrawnLeadingToShot { get; set; }
        public int? TeamOneGoalCreatingActions { get; set; }
        public int? TeamOnePassesCompletedLiveBallLeadingToGoal { get; set; }
        public int? TeamOnePassesCompletedDeadBallLeadingToGoal { get; set; }
        public int? TeamOneDribblesLeadingToGoal { get; set; }
        public int? TeamOneGoalsLeadingToAnotherGoal { get; set; }
        public int? TeamOneFoulsDrawnLeadingToGoal { get; set; }
        public int? TeamOneActionsLeadingToOpponentOwnGoal { get; set; }
        public int? TeamOnePlayersTackled { get; set; }
        public int? TeamOneTacklesWon { get; set; }
        public int? TeamOneTacklesDefensiveThird { get; set; }
        public int? TeamOneTacklesMiddleThird { get; set; }
        public int? TeamOneTacklesAttackingThird { get; set; }
        public int? TeamOneDribblersTackled { get; set; }
        public int? TeamOneDribblesContested { get; set; }
        public double? TeamOneDribblersTackledPercentage { get; set; }
        public int? TeamOneTimesDribbledPast { get; set; }
        public int? TeamOnePressures { get; set; }
        public int? TeamOneSuccessfulPressures { get; set; }
        public double? TeamOneSuccessfulPressuresPercentage { get; set; }
        public int? TeamOnePressuresDefensiveThird { get; set; }
        public int? TeamOnePressuresMiddleThird { get; set; }
        public int? TeamOnePressuresAttackingThird { get; set; }
        public int? TeamOneBlocks { get; set; }
        public int? TeamOneShotsBlocked { get; set; }
        public int? TeamOneShotsOnTargetBlocked { get; set; }
        public int? TeamOnePassesBlocked { get; set; }
        public int? TeamOneInterceptions { get; set; }
        public int? TeamOnePlayersTackledAndInterceptions { get; set; }
        public int? TeamOneClearances { get; set; }
        public int? TeamOneErrorsLeadingToShot { get; set; }
        public int? TeamTwoGoals { get; set; }
        public int? TeamTwoShots { get; set; }
        public int? TeamTwoShotsOnTarget { get; set; }
        public double? TeamTwoShotsOnTargetPercentage { get; set; }
        public double? TeamTwoShotsPerTouch { get; set; }
        public double? TeamTwoGoalsPerShot { get; set; }
        public int? TeamTwoPenaltyKicksMade { get; set; }
        public int? TeamTwoPenaltyKicksAttempted { get; set; }
        public double? TeamTwoPenaltyKicksConversionRate { get; set; }
        public decimal? TeamTwoXG { get; set; }
        public decimal? TeamTwoNonPenaltyXG { get; set; }
        public double? TeamTwoNonPenaltyXGPerShot { get; set; }
        public decimal? TeamTwoGoalsMinusXG { get; set; }
        public decimal? TeamTwoNonPenaltyGoalsMinusXG { get; set; }
        public int? TeamTwoTouchesDefensivePenaltyArea { get; set; }
        public int? TeamTwoTouchesDefensiveThird { get; set; }
        public int? TeamTwoTouchesMiddleThird { get; set; }
        public int? TeamTwoTouchesAttackingThird { get; set; }
        public int? TeamTwoTouchesAttackingPenaltyArea { get; set; }
        public int? TeamTwoTouches { get; set; }
        public int? TeamTwoLiveBallTouches { get; set; }
        public int? TeamTwoDribblesAttempted { get; set; }
        public int? TeamTwoSuccessfulDribbles { get; set; }
        public double? TeamTwoSuccessfulDribblesPercentage { get; set; }
        public int? TeamTwoPlayersDribbledPast { get; set; }
        public int? TeamTwoPassesReceived { get; set; }
        public double? TeamTwoPassesReceivedPercentage { get; set; }
        public int? TeamTwoMiscontrols { get; set; }
        public int? TeamTwoDispossessed { get; set; }
        public int? TeamTwoPassesAttemptedLiveBall { get; set; }
        public int? TeamTwoPassesAttemptedDeadBall { get; set; }
        public int? TeamTwoPassesAttemptedFreeKick { get; set; }
        public int? TeamTwoPassesCompletedThroughBall { get; set; }
        public int? TeamTwoPassesCompletedUnderPressure { get; set; }
        public int? TeamTwoSwitches { get; set; }
        public int? TeamTwoCrosses { get; set; }
        public int? TeamTwoCornerKicks { get; set; }
        public int? TeamTwoCornerKicksInswinging { get; set; }
        public int? TeamTwoCornerKicksOutswinging { get; set; }
        public int? TeamTwoCornerKicksStraight { get; set; }
        public int? TeamTwoPassesGround { get; set; }
        public int? TeamTwoPassesLow { get; set; }
        public int? TeamTwoPassesHigh { get; set; }
        public int? TeamTwoPassesLeftFoot { get; set; }
        public int? TeamTwoPassesRightFoot { get; set; }
        public int? TeamTwoPassesHeaded { get; set; }
        public int? TeamTwoPassesThrowIn { get; set; }
        public int? TeamTwoPassesOther { get; set; }
        public int? TeamTwoPassesOffside { get; set; }
        public int? TeamTwoPassesOutOfBounds { get; set; }
        public int? TeamTwoPassesAttemptedIntercepted { get; set; }
        public int? TeamTwoPassesAttemptedBlocked { get; set; }
        public int? TeamTwoPassesCompleted { get; set; }
        public int? TeamTwoPassesAttempted { get; set; }
        public double? TeamTwoPassesCompletedPercentage { get; set; }
        public int? TeamTwoYardsPassed { get; set; }
        public int? TeamTwoYardsPassedProgressive { get; set; }
        public int? TeamTwoShortPassesCompleted { get; set; }
        public int? TeamTwoShortPassesAttempted { get; set; }
        public double? TeamTwoShortPassesCompletedPercentage { get; set; }
        public int? TeamTwoMediumPassesCompleted { get; set; }
        public int? TeamTwoMediumPassesAttempted { get; set; }
        public double? TeamTwoMediumPassesCompletedPercentage { get; set; }
        public int? TeamTwoLongPassesCompleted { get; set; }
        public int? TeamTwoLongPassesAttempted { get; set; }
        public double? TeamTwoLongPassesCompletedPercentage { get; set; }
        public int? TeamTwoAssists { get; set; }
        public decimal? TeamTwoXGAssisted { get; set; }
        public int? TeamTwoKeyPasses { get; set; }
        public int? TeamTwoChancesCreated { get; set; }
        public int? TeamTwoPassesIntoFinalThird { get; set; }
        public int? TeamTwoPassesIntoPenaltyArea { get; set; }
        public int? TeamTwoCrossesIntoPenaltyArea { get; set; }
        public int? TeamTwoProgressivePasses { get; set; }
        public double? TeamTwoProgressivePassesPercentage { get; set; }
        public int? TeamTwoYellowCards { get; set; }
        public int? TeamTwoRedCards { get; set; }
        public int? TeamTwoFouls { get; set; }
        public int? TeamTwoFoulsDrawn { get; set; }
        public int? TeamTwoOffsides { get; set; }
        public int? TeamTwoPenaltyKicksConceded { get; set; }
        public int? TeamTwoOwnGoals { get; set; }
        public int? TeamTwoLooseBallsRecovered { get; set; }
        public int? TeamTwoAerialDualsWon { get; set; }
        public int? TeamTwoAerialDualsLost { get; set; }
        public double? TeamTwoAerialDualsWonPercentage { get; set; }
        public int? TeamTwoGkGoalsConceded { get; set; }
        public int? TeamTwoGkSaves { get; set; }
        public double? TeamTwoGkSavesPercentage { get; set; }
        public int? TeamTwoGkCleanSheets { get; set; }
        public decimal? TeamTwoGkPostShotXG { get; set; }
        public int? TeamTwoGkPassesCompletedOver40Yards { get; set; }
        public int? TeamTwoGkPassesAttemptedOver40Yards { get; set; }
        public double? TeamTwoGkPassesCompletedOver40YardsPercentage { get; set; }
        public int? TeamTwoGkThrowsAttempted { get; set; }
        public double? TeamTwoGkPassesAttemptedOver40YardsPercentage { get; set; }
        public int? TeamTwoGkGoalKicksAttempted { get; set; }
        public int? TeamTwoGkOpponentCrossesAttempted { get; set; }
        public double? TeamTwoGkOpponentCrossesStoppedPercentage { get; set; }
        public int? TeamTwoGkDefensiveActionsOutsidePenaltyArea { get; set; }
        public int? TeamTwoShotCreatingActions { get; set; }
        public int? TeamTwoPassesCompletedLiveBallLeadingToShot { get; set; }
        public int? TeamTwoPassesCompletedDeadBallLeadingToShot { get; set; }
        public int? TeamTwoDribblesLeadingToShot { get; set; }
        public int? TeamTwoShotsLeadingToAnotherShot { get; set; }
        public int? TeamTwoFoulsDrawnLeadingToShot { get; set; }
        public int? TeamTwoGoalCreatingActions { get; set; }
        public int? TeamTwoPassesCompletedLiveBallLeadingToGoal { get; set; }
        public int? TeamTwoPassesCompletedDeadBallLeadingToGoal { get; set; }
        public int? TeamTwoDribblesLeadingToGoal { get; set; }
        public int? TeamTwoGoalsLeadingToAnotherGoal { get; set; }
        public int? TeamTwoFoulsDrawnLeadingToGoal { get; set; }
        public int? TeamTwoActionsLeadingToOpponentOwnGoal { get; set; }
        public int? TeamTwoPlayersTackled { get; set; }
        public int? TeamTwoTacklesWon { get; set; }
        public int? TeamTwoTacklesDefensiveThird { get; set; }
        public int? TeamTwoTacklesMiddleThird { get; set; }
        public int? TeamTwoTacklesAttackingThird { get; set; }
        public int? TeamTwoDribblersTackled { get; set; }
        public int? TeamTwoDribblesContested { get; set; }
        public double? TeamTwoDribblersTackledPercentage { get; set; }
        public int? TeamTwoTimesDribbledPast { get; set; }
        public int? TeamTwoPressures { get; set; }
        public int? TeamTwoSuccessfulPressures { get; set; }
        public double? TeamTwoSuccessfulPressuresPercentage { get; set; }
        public int? TeamTwoPressuresDefensiveThird { get; set; }
        public int? TeamTwoPressuresMiddleThird { get; set; }
        public int? TeamTwoPressuresAttackingThird { get; set; }
        public int? TeamTwoBlocks { get; set; }
        public int? TeamTwoShotsBlocked { get; set; }
        public int? TeamTwoShotsOnTargetBlocked { get; set; }
        public int? TeamTwoPassesBlocked { get; set; }
        public int? TeamTwoInterceptions { get; set; }
        public int? TeamTwoPlayersTackledAndInterceptions { get; set; }
        public int? TeamTwoClearances { get; set; }
        public int? TeamTwoErrorsLeadingToShot { get; set; }
    }
}
