using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace AkriStat.Models
{
    public partial class TeamMatchLogSummaries
    {
        public int? TeamID { get; set; }
        public string TeamName { get; set; }
        public string Season { get; set; }
        public int? GamesPlayed { get; set; }
        public int? MinutesPlayed { get; set; }
        public int? Goals { get; set; }
        public double GoalsPerGame { get; set; }
        public int? Shots { get; set; }
        public double ShotsPerGame { get; set; }
        public int? ShotsOnTarget { get; set; }
        public double ShotsOnTargetPerGame { get; set; }
        public double ShotsOnTargetPercentage { get; set; }
        public decimal AverageShotsOnTargetPercentage { get; set; }
        public double ShotsPerTouch { get; set; }
        public double GoalsPerShot { get; set; }
        public int? PenaltyKicksMade { get; set; }
        public double PenaltyKicksMadePerGame { get; set; }
        public int? PenaltyKicksAttempted { get; set; }
        public double PenaltyKicksConversionRate { get; set; }
        public double PenaltyKicksAttemptedPerGame { get; set; }
        public decimal? XG { get; set; }
        public double XGPerGame { get; set; }
        public decimal? NonPenaltyXG { get; set; }
        public double NonPenaltyXGPerGame { get; set; }
        public double NonPenaltyXGPerShot { get; set; }
        public decimal? GoalsMinusXG { get; set; }
        public decimal? NonPenaltyGoalsMinusXG { get; set; }
        public int? TouchesDefensivePenaltyArea { get; set; }
        public double TouchesDefensivePenaltyAreaPerGame { get; set; }
        public int? TouchesDefensiveThird { get; set; }
        public double TouchesDefensiveThirdPerGame { get; set; }
        public int? TouchesMiddleThird { get; set; }
        public double TouchesMiddleThirdPerGame { get; set; }
        public int? TouchesAttackingThird { get; set; }
        public double TouchesAttackingThirdPerGame { get; set; }
        public int? TouchesAttackingPenaltyArea { get; set; }
        public double TouchesAttackingPenaltyAreaPerGame { get; set; }
        public int? Touches { get; set; }
        public double TouchesPerGame { get; set; }
        public int? LiveBallTouches { get; set; }
        public double LiveBallTouchesPerGame { get; set; }
        public int? DribblesAttempted { get; set; }
        public double DribblesAttemptedPerGame { get; set; }
        public int? SuccessfulDribbles { get; set; }
        public double SuccessfulDribblesPerGame { get; set; }
        public double SuccessfulDribblesPercentage { get; set; }
        public decimal? AverageSuccessfulDribblesPercentage { get; set; }
        public int? PlayersDribbledPast { get; set; }
        public double PlayersDribbledPastPerGame { get; set; }
        public int? Nutmegs { get; set; }
        public double NutmegsPerGame { get; set; }
        public int? Carries { get; set; }
        public double CarriesPerGame { get; set; }
        public int? YardsCarried { get; set; }
        public double YardsCarriedPerGame { get; set; }
        public int? YardsProgressiveCarries { get; set; }
        public double YardsProgressiveCarriesPerGame { get; set; }
        public double? YardsPerCarry { get; set; }
        public int? WasTargetOfPass { get; set; }
        public double WasTargetOfPassPerGame { get; set; }
        public int? PassesReceived { get; set; }
        public double PassesReceivedPerGame { get; set; }
        public double PassesReceivedPercentage { get; set; }
        public decimal? AveragePassesReceivedPercentage { get; set; }
        public int? Miscontrols { get; set; }
        public double MiscontrolsPerGame { get; set; }
        public int? Dispossessed { get; set; }
        public double DispossessedPerGame { get; set; }
        public int? PassesAttemptedLiveBall { get; set; }
        public double PassesAttemptedLiveBallPerGame { get; set; }
        public int? PassesAttemptedDeadBall { get; set; }
        public double PassesAttemptedDeadBallPerGame { get; set; }
        public int? PassesAttemptedFreeKick { get; set; }
        public double PassesAttemptedFreeKickPerGame { get; set; }
        public int? PassesCompletedThroughBall { get; set; }
        public double PassesCompletedThroughBallPerGame { get; set; }
        public int? PassesCompletedUnderPressure { get; set; }
        public double PassesCompletedUnderPressurePerGame { get; set; }
        public int? Switches { get; set; }
        public double SwitchesPerGame { get; set; }
        public int? Crosses { get; set; }
        public double CrossesPerGame { get; set; }
        public int? CornerKicks { get; set; }
        public double CornerKicksPerGame { get; set; }
        public int? CornerKicksInswinging { get; set; }
        public double CornerKicksInswingingPerGame { get; set; }
        public int? CornerKicksOutswinging { get; set; }
        public double CornerKicksOutswingingPerGame { get; set; }
        public int? CornerKicksStraight { get; set; }
        public double CornerKicksStraightPerGame { get; set; }
        public int? PassesGround { get; set; }
        public double PassesGroundPerGame { get; set; }
        public int? PassesLow { get; set; }
        public double PassesLowPerGame { get; set; }
        public int? PassesHigh { get; set; }
        public double PassesHighPerGame { get; set; }
        public int? PassesLeftFoot { get; set; }
        public double PassesLeftFootPerGame { get; set; }
        public int? PassesRightFoot { get; set; }
        public double PassesRightFootPerGame { get; set; }
        public int? PassesHeaded { get; set; }
        public double PassesHeadedPerGame { get; set; }
        public int? PassesThrowIn { get; set; }
        public double PassesThrowInPerGame { get; set; }
        public int? PassesOther { get; set; }
        public double PassesOtherPerGame { get; set; }
        public int? PassesOffside { get; set; }
        public double PassesOffsidePerGame { get; set; }
        public int? PassesOutOfBounds { get; set; }
        public double PassesOutOfBoundsPerGame { get; set; }
        public int? PassesAttemptedIntercepted { get; set; }
        public double PassesAttemptedInterceptedPerGame { get; set; }
        public int? PassesAttemptedBlocked { get; set; }
        public double PassesAttemptedBlockedPerGame { get; set; }
        public int? PassesCompleted { get; set; }
        public double PassesCompletedPerGame { get; set; }
        public int? PassesAttempted { get; set; }
        public double PassesAttemptedPerGame { get; set; }
        public decimal? AveragePassesCompletedPercentage { get; set; }
        public double PassesCompletedPercentage { get; set; }
        public int? YardsPassed { get; set; }
        public double YardsPassedPerGame { get; set; }
        public int? YardsPassedProgressive { get; set; }
        public double YardsPassedProgressivePerGame { get; set; }
        public int? ShortPassesCompleted { get; set; }
        public double ShortPassesCompletedPerGame { get; set; }
        public int? ShortPassesAttempted { get; set; }
        public double ShortPassesAttemptedPerGame { get; set; }
        public decimal? AverageShortPassesCompletedPercentage { get; set; }
        public double ShortPassesCompletedPercentage { get; set; }
        public int? MediumPassesCompleted { get; set; }
        public double MediumPassesCompletedPerGame { get; set; }
        public int? MediumPassesAttempted { get; set; }
        public double MediumPassesAttemptedPerGame { get; set; }
        public decimal? AverageMediumPassesCompletedPercentage { get; set; }
        public double MediumPassesCompletedPercentage { get; set; }
        public int? LongPassesCompleted { get; set; }
        public double LongPassesCompletedPerGame { get; set; }
        public int? LongPassesAttempted { get; set; }
        public double LongPassesAttemptedPerGame { get; set; }
        public decimal? AverageLongPassesCompletedPercentage { get; set; }
        public double LongPassesCompletedPercentage { get; set; }
        public int? Assists { get; set; }
        public double AssistsPerGame { get; set; }
        public decimal? XGAssisted { get; set; }
        public double XGAssistedPerGame { get; set; }
        public int? KeyPasses { get; set; }
        public double KeyPassesPerGame { get; set; }
        public int? ChancesCreated { get; set; }
        public double ChancesCreatedPerGame { get; set; }
        public int? PassesIntoFinalThird { get; set; }
        public double PassesIntoFinalThirdPerGame { get; set; }
        public int? PassesIntoPenaltyArea { get; set; }
        public double PassesIntoPenaltyAreaPerGame { get; set; }
        public int? CrossesIntoPenaltyArea { get; set; }
        public double CrossesIntoPenaltyAreaPerGame { get; set; }
        public int? ProgressivePasses { get; set; }
        public double ProgressivePassesPerGame { get; set; }
        public decimal? AverageProgressivePassesPercentage { get; set; }
        public double ProgressivePassesPercentage { get; set; }
        public int? YellowCards { get; set; }
        public int? RedCards { get; set; }
        public int? Fouls { get; set; }
        public double FoulsPerGame { get; set; }
        public int? FoulsDrawn { get; set; }
        public double FoulsDrawnPerGame { get; set; }
        public int? Offsides { get; set; }
        public double OffsidesPerGame { get; set; }
        public int? PenaltyKicksConceded { get; set; }
        public double PenaltyKicksConcededPerGame { get; set; }
        public int? OwnGoals { get; set; }
        public double OwnGoalsPerGame { get; set; }
        public int? LooseBallsRecovered { get; set; }
        public double LooseBallsRecoveredPerGame { get; set; }
        public int? AerialDualsWon { get; set; }
        public double AerialDualsWonPerGame { get; set; }
        public int? AerialDualsLost { get; set; }
        public double AerialDualsLostPerGame { get; set; }
        public decimal? AverageAerialDualsWonPercentage { get; set; }
        public double AerialDualsWonPercentage { get; set; }
        public double GkShotsOnTargetFacedPerGame { get; set; }
        public int? GkGoalsConceded { get; set; }
        public double GkGoalsConcededPerGame { get; set; }
        public int? GkSaves { get; set; }
        public double GkSavesPerGame { get; set; }
        public decimal? GkAverageSavesPercentage { get; set; }
        public double GkSavesPercentage { get; set; }
        public int? GkCleanSheets { get; set; }
        public decimal? GkPostShotXG { get; set; }
        public double GkPostShotXGPerGame { get; set; }
        public int? GkPassesCompletedOver40Yards { get; set; }
        public double GkPassesCompletedOver40YardsPerGame { get; set; }
        public int? GkPassesAttemptedOver40Yards { get; set; }
        public double GkPassesAttemptedOver40YardsPerGame { get; set; }
        public decimal? GkAveragePassesCompletedOver40YardsPercentage { get; set; }
        public double GkPassesCompletedOver40YardsPercentage { get; set; }
        public int? GkThrowsAttempted { get; set; }
        public double GkThrowsAttemptedPerGame { get; set; }
        public decimal? GkAveragePassesAttemptedOver40YardsPercentage { get; set; }
        public double GkPassesAttemptedOver40YardsPercentage { get; set; }
        public decimal? GkAverageYardsPassLength { get; set; }
        public int? GkGoalKicksAttempted { get; set; }
        public double GkGoalKicksAttemptedPerGame { get; set; }
        public decimal? GkAverageGoalKicksLaunchedPercentage { get; set; }
        public decimal? GkGoalKickAverageYards { get; set; }
        public int? GkOpponentCrossesAttempted { get; set; }
        public decimal? GkAverageCrossesStoppedPercentage { get; set; }
        public double GkOpponentCrossesStoppedPercentage { get; set; }
        public int? GkDefensiveActionsOutsidePenaltyArea { get; set; }
        public double GkDefensiveActionsOutsidePenaltyAreaPerGame { get; set; }
        public decimal? GkAverageDistanceFromGoalForDefensiveActions { get; set; }
        public int? ShotCreatingActions { get; set; }
        public double ShotCreatingActionsPerGame { get; set; }
        public int? PassesCompletedLiveBallLeadingToShot { get; set; }
        public double PassesCompletedLiveBallLeadingToShotPerGame { get; set; }
        public int? PassesCompletedDeadBallLeadingToShot { get; set; }
        public double PassesCompletedDeadBallLeadingToShotPerGame { get; set; }
        public int? DribblesLeadingToShot { get; set; }
        public double DribblesLeadingToShotPerGame { get; set; }
        public int? ShotsLeadingToAnotherShot { get; set; }
        public double ShotsLeadingToAnotherShotPerGame { get; set; }
        public int? FoulsDrawnLeadingToShot { get; set; }
        public double FoulsDrawnLeadingToShotPerGame { get; set; }
        public int? GoalCreatingActions { get; set; }
        public double GoalCreatingActionsPerGame { get; set; }
        public int? PassesCompletedLiveBallLeadingToGoal { get; set; }
        public double PassesCompletedLiveBallLeadingToGoalPerGame { get; set; }
        public int? PassesCompletedDeadBallLeadingToGoal { get; set; }
        public double PassesCompletedDeadBallLeadingToGoalPerGame { get; set; }
        public int? DribblesLeadingToGoal { get; set; }
        public double DribblesLeadingToGoalPerGame { get; set; }
        public int? GoalsLeadingToAnotherGoal { get; set; }
        public double ShotsLeadingToAnotherGoalPerGame { get; set; }
        public int? FoulsDrawnLeadingToGoal { get; set; }
        public double FoulsDrawnLeadingToGoalPerGame { get; set; }
        public int? ActionsLeadingToOpponentOwnGoal { get; set; }
        public double ActionsLeadingToOpponentOwnGoalPerGame { get; set; }
        public int? PlayersTackled { get; set; }
        public double PlayersTackledPerGame { get; set; }
        public int? TacklesWon { get; set; }
        public double TacklesWonPerGame { get; set; }
        public double TacklesWonPercentage { get; set; }
        public int? TacklesDefensiveThird { get; set; }
        public int? TacklesMiddleThird { get; set; }
        public int? TacklesAttackingThird { get; set; }
        public int? DribblersTackled { get; set; }
        public int? DribblesContested { get; set; }
        public decimal? AverageDribblersTackledPercentage { get; set; }
        public double DribblersTackledPercentage { get; set; }
        public int? TimesDribbledPast { get; set; }
        public double TimesDribbledPastPerGame { get; set; }
        public int? Pressures { get; set; }
        public double PressuresPerGame { get; set; }
        public int? SuccessfulPressures { get; set; }
        public double SuccessfulPressuresPerGame { get; set; }
        public decimal? AverageSuccessfulPressuresPercentage { get; set; }
        public double SuccessfulPressuresPercentage { get; set; }
        public int? PressuresDefensiveThird { get; set; }
        public int? PressuresMiddleThird { get; set; }
        public int? PressuresAttackingThird { get; set; }
        public int? Blocks { get; set; }
        public double BlocksPerGame { get; set; }
        public int? ShotsBlocked { get; set; }
        public int? ShotsOnTargetBlocked { get; set; }
        public int? PassesBlocked { get; set; }
        public int? Interceptions { get; set; }
        public double InterceptionsPerGame { get; set; }
        public int? PlayersTackledAndInterceptions { get; set; }
        public double PlayersTackledAndInterceptionsPerGame { get; set; }
        public int? Clearances { get; set; }
        public double ClearancesPerGame { get; set; }
        public int? ErrorsLeadingToShot { get; set; }
        public double ErrorsLeadingToShotPerGame { get; set; }
    }
}
